### ISSUE TITLE
Some node modules block the execution

### ISSUE THREAD

**Issue by jerome-fox** [medikoo/serverless-plugin-lambda-reducer#3]
When I try to reduce a lambda using the 'mongoose' module or the 'redis' module, then the treatment blocks.

After some investigations, the plugin stops to these files:

> node_modules/mongoose/lib/index.js
> node_modules/redis-parser/lib/hiredis.js

**Comment by medikoo** [comment]
Thanks @jerome-fox for report. We also observed that on our side (e.g. when trying to import `pupetter`).

I'll try to look into it shortly

**Comment by jerome-fox** [comment]
Thanks!

If it helps, my investigation stops in the module 'cjs-module' in the function 'getDirectDependencies'

**Comment by medikoo** [comment]
I coined one bug in deep dependency that was most likely responsible for that blocking

Please ensure that in your dependency tree you rely on deferred at `v0.7.10` or greater (I'd also shortly update this package, so it ensures to rely fixed version).

**Comment by medikoo** [comment]
I double checked, and there was also issue in other dependency (`find-requires`).

It's fixed now, and I released new version of this package to ensure it gets fixed dependencies.

Additionally tests with solid coverage were added.

Be sure to rely on  `^3.1.1`
